/**
 * Browser Inspection Module
 *
 * Provides client-side code inspection capabilities for analyzing running web3 applications.
 * Fetches JavaScript sources from the current page and analyzes transaction/signing patterns
 * to generate security reports via the Rukh API.
 *
 * This module is designed to be used directly in the browser console or embedded in
 * web applications to help end-users understand the security posture of the apps they use.
 *
 * @module inspect/browser
 */

/**
 * Configuration options for browser-based application inspection
 */
export interface BrowserInspectOptions {
  /**
   * The origin/URL of the app to inspect
   * @default window.location.origin
   */
  appUrl?: string;

  /**
   * Rukh API endpoint
   * @default 'https://rukh.w3hc.org'
   */
  rukhUrl?: string;

  /**
   * Context to use for analysis
   * @default 'w3pk'
   */
  context?: string;

  /**
   * AI model to use
   * @default 'anthropic'
   */
  model?: "anthropic" | "mistral" | "openai";

  /**
   * Focus mode for analysis
   * @default 'transactions'
   */
  focusMode?: "transactions" | "all";
}

/**
 * Result of a browser-based inspection
 */
export interface BrowserInspectResult {
  /**
   * The security report markdown generated by Rukh API
   */
  report: string;

  /**
   * List of JavaScript file paths that were analyzed
   */
  analyzedFiles: string[];

  /**
   * The application URL that was inspected
   */
  appUrl: string;
}

/**
 * Extracts transaction-related code snippets from JavaScript content
 *
 * Scans JavaScript code for keywords related to signing, transactions, and web3 operations,
 * then extracts relevant code snippets with surrounding context.
 *
 * @param content - The JavaScript source code to analyze
 * @param maxLength - Maximum length of extracted snippets in characters
 * @returns Extracted code snippets or a message if no relevant code found
 * @internal
 */
function extractTransactionSnippets(
  content: string,
  maxLength: number = 30000,
): string {
  const keywords = [
    "signMessage",
    "signTypedData",
    "sign(",
    "signature",
    "sendTransaction",
    "transaction",
    "eth_sign",
    "Contract(",
    "ethers.Contract",
    "new Contract",
    "w3pk",
    "Web3Passkey",
    "useW3PK",
    "wallet",
    "signer",
    "provider",
    "authorization",
    "delegation",
    "EIP7702",
  ];

  const lines = content.split("\n");
  const relevantLines: string[] = [];
  const maxLines = 500;

  for (let i = 0; i < lines.length && relevantLines.length < maxLines; i++) {
    const line = lines[i];
    const lowerLine = line.toLowerCase();

    if (keywords.some((kw) => lowerLine.includes(kw.toLowerCase()))) {
      const start = Math.max(0, i - 2);
      const end = Math.min(lines.length, i + 3);

      for (let j = start; j < end; j++) {
        if (!relevantLines.includes(lines[j])) {
          relevantLines.push(lines[j]);
        }
      }
    }
  }

  const snippet = relevantLines.join("\n");

  if (snippet.length > maxLength) {
    return snippet.substring(0, maxLength) + "\n\n// ... (truncated)";
  }

  return snippet || "// No transaction code found";
}

/**
 * Fetches JavaScript source code from the currently running application
 *
 * Discovers and fetches all script tags in the current page, extracts transaction-related
 * snippets, and formats them as markdown for analysis.
 *
 * @param appUrl - The base URL of the application being inspected
 * @returns Markdown-formatted source code with transaction-related snippets
 * @internal
 */
async function fetchAppSource(appUrl: string): Promise<string> {
  let markdown = `# Application Code Analysis\n\n`;
  markdown += `**App URL:** ${appUrl}\n\n`;
  markdown += `**Note:** Only transaction-related code snippets shown\n\n`;
  markdown += `---\n\n`;

  const scripts = Array.from(document.querySelectorAll("script[src]"));
  const scriptUrls = scripts
    .map((script) => (script as HTMLScriptElement).src)
    .filter(
      (src) =>
        src &&
        !src.includes("node_modules") &&
        !src.includes("chrome-extension"),
    );

  markdown += `## JavaScript Files (${scriptUrls.length})\n\n`;

  let totalSnippets = 0;

  for (const scriptUrl of scriptUrls.slice(0, 15)) {
    try {
      const response = await fetch(scriptUrl);
      if (!response.ok) continue;

      const content = await response.text();
      const snippets = extractTransactionSnippets(content);

      if (snippets && !snippets.includes("No transaction code found")) {
        markdown += `### \`${new URL(scriptUrl).pathname}\`\n\n`;
        markdown += "```javascript\n";
        markdown += snippets;
        markdown += "\n```\n\n---\n\n";
        totalSnippets++;
      }
    } catch (error) {
      // Skip files that can't be fetched
    }
  }

  if (totalSnippets === 0) {
    markdown += `No transaction-related code found in JavaScript files.\n`;
  }

  return markdown;
}

/**
 * Inspects the currently running web application and returns a security report
 *
 * This function can be called by end-users in their browser console to analyze
 * the security of the web application they're currently using.
 *
 * @param options - Configuration options
 * @returns A security report analyzing transaction and signing methods
 *
 * @example
 * ```typescript
 * // In browser console or app code:
 * import { inspect } from 'w3pk';
 *
 * const report = await inspect();
 * console.log(report.report);
 * ```
 *
 * @example
 * ```typescript
 * // With custom options:
 * const report = await inspect({
 *   appUrl: 'https://w3pk.w3hc.org',
 *   model: 'anthropic',
 *   focusMode: 'transactions'
 * });
 * ```
 */
export async function inspect(
  options: BrowserInspectOptions = {},
): Promise<BrowserInspectResult> {
  // Check if running in browser
  if (typeof window === "undefined") {
    throw new Error(
      "Browser inspect() can only be called in browser environments. For Node.js, use the CLI or Node.js API.",
    );
  }

  const {
    appUrl = window.location.origin,
    rukhUrl = "https://rukh.w3hc.org",
    context = "w3pk",
    model = "anthropic",
    focusMode = "transactions",
  } = options;

  console.log("[W3PK Inspect] Starting inspection of", appUrl);
  console.log("[W3PK Inspect] Focus mode:", focusMode);

  // Fetch and analyze source code
  const sourceMarkdown = await fetchAppSource(appUrl);

  console.log("[W3PK Inspect] Collected source code, sending to Rukh API...");

  // Prepare request to Rukh API
  const message =
    "Analyze this web application and provide a security report listing all transaction and signing methods.";

  const formData = new FormData();
  formData.append("message", message);
  formData.append("model", model);
  formData.append("context", context);

  // Create blob from markdown
  const blob = new Blob([sourceMarkdown], { type: "text/markdown" });
  formData.append("file", blob, "app-source.md");

  // Send to Rukh API
  const response = await fetch(`${rukhUrl}/ask`, {
    method: "POST",
    body: formData,
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Rukh API error: ${response.status} - ${error}`);
  }

  const data = await response.json();
  const report =
    data.output || data.response || data.message || JSON.stringify(data);

  console.log("[W3PK Inspect] Analysis complete!");

  // Extract script URLs for analyzedFiles
  const scripts = Array.from(document.querySelectorAll("script[src]"));
  const analyzedFiles = scripts
    .map((script) => new URL((script as HTMLScriptElement).src).pathname)
    .filter((src) => src && !src.includes("node_modules"));

  return {
    report,
    analyzedFiles,
    appUrl,
  };
}

/**
 * Quick inspection helper that logs the report to console
 * Perfect for use in browser DevTools console
 *
 * @example
 * ```javascript
 * // In browser console:
 * await w3pk.inspectNow()
 * ```
 */
export async function inspectNow(
  options?: BrowserInspectOptions,
): Promise<void> {
  console.log("🔍 W3PK Security Inspection Starting...\n");

  try {
    const result = await inspect(options);

    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log("📋 SECURITY REPORT");
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
    console.log(result.report);
    console.log("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log(
      `✅ Analyzed ${result.analyzedFiles.length} files from ${result.appUrl}`,
    );
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  } catch (error) {
    console.error("❌ Inspection failed:", error);
    throw error;
  }
}
